react-navigation/tabs

- package.json
- yarn.lock
Missing babel-cli dependency is causing yarn install to fail:
```
$ yarn install
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-native-paper@1.2.4" has unmet peer dependency "react-native-vector-icons@*".
warning " > babel-jest@21.2.0" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0".
[4/4] 📃  Building fresh packages...
$ yarn build
yarn run v1.3.2
$ babel --no-babelrc --plugins=syntax-jsx,syntax-class-properties,syntax-object-rest-spread,transform-flow-strip-types src --out-dir dist --ignore '**/__tests__/**'
/bin/sh: babel: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. …
```
> chore: add the missing babel-cli

- src/utils/createTabNavigator.js
The action helpers may not be available at the navigator level, they will be there inside the screen.
This change dispatches a normal explicit action, without relying on the helper. Alternatively we could use a child navigation prop on a screen descriptor, but this is easier right now.
> Fix tab action in for react nav v2

- package.json
- src/navigators/createMaterialTopTabNavigator.js
- src/utils/createTabNavigator.js
- src/views/BottomTabBar.js
Right now `tabBarOnPress` is ignored. This PR hooks it up to `react-native-tab-view`'s `onTabPress`, and uses the new `react-navigation@2.0` parameter type (an object containing a single property, which is the `navigation` prop).
> Hook up tabBarOnPress

- src/navigators/createBottomTabNavigator.js
- src/navigators/createMaterialTopTabNavigator.js
- src/utils/createTabNavigator.js
- src/views/BottomTabBar.js
- src/views/MaterialTopTabBar.js
The accessibilityLabel and testID could be set for tab bar items in version 1.
I reused the implementation from 1.5.11. The navigationOptions can contain the accessibilityLabel and testID like this:
`tabBarTestIDProps: {
accessibilityLabel: 'Label',
testID: 'TestID',
},`
Allow making apps accessible and allow for automated UI testing.
Create an app with a bottom tab bar. Add `tabBarTestIDProps` to the the navigation options of the tabs. Then run the app and use Accessibility Inspector for iOS and uiautomatorviewer to inspect the tabs.
> Add accessibilityLabel and testID to BottomTabBar

- src/views/BottomTabBar.js
We want to show content below the tab view, which behaved poorly on iPhone X because of the content safe area being added automatically. I added the ability to override this behaviour.
Create a BottomTabBar view and add content below it on iPhone X, then change the new `safeAreaInset` property.
> Allows use of custom safe area inset

- src/views/BottomTabBar.js
I believe `defaultProps` are better suited for this than the `||` approach.
Since the change is small I believe in-depth testing is not necessary. I just pasted this into my project that uses tabs and it seems to work. Hope this is good enough :D
> use defaultProps instead of ||

- src/navigators/createBottomTabNavigator.js
- src/navigators/createMaterialTopTabNavigator.js
- src/utils/createTabNavigator.js
- src/views/ResourceSavingScene.js
Routes in `MaterialTopTabNavigator` are now lazy initialized like in `MaterialBottomTabNavigator`.
A scene visibility is computed from multiple states and props:
To handle the pan between tabs, we check if you're currently swiping between tabs and the prop `lazyOnSwipe` is true (default value) or if the tab have been already loaded, we'll check if this tab is a sibling of the focused tab. Then, we'll display the tab if it's a sibling.
~With the prop `animationEnabled` to true, we shouldn't hide a tab before the transition is done. So we're waiting `COMPLETE_TRANSITION` action to hide it. Also, if the prop `sceneAlwaysVisible` is true (default value), we won't hide scenes between A and D while transitioning.~
If the current tab has not been loaded and must not be visible, we do not render …
> Lazy initialized MaterialTopTabNavigator routes

- package.json
- src/views/BottomTabBar.js
- yarn.lock
Upgrades `react-native-safe-area-view` to make a warning go away (`Cannot call setState() while not mounted...`)
> Upgrade react-native-safe-area-view

- package.json
- src/navigators/createBottomTabNavigator.js
- src/views/ResourceSavingScene.js
- yarn.lock
This change adds support for react-native-screens. Screens package makes it possible to use native primitives to render tabs container and its scenes such that they get properly mounted/unmounted when not visible.
The support has only been added to `createBottomTabNavigator` as the material one renders its own container that's a part of a different package (react-native-tab-view).
For bottom tabs component we use `screensEnabled` method to tell if screens support is enabled for the app. We do that because by default Screen and ScreenContainer fallsback to regular View whereas in case of bottom tabs we want to fallback to ResourceSavingScene.
Run bottom tabs sample application. With tabs on screen take view hierarchy snapshot (Debug > View Debugging menu on iOS or Tools > Layout Inspector …
> Use react-native-screens when available

- package.json
By shipping source files and setting the ‘react-native’ entry point to src, the RN packager can parse the module and provide source maps when debugging from your app. This makes the install slightly heavier but is worth it for the improved ergonomics.
> Distribute source

- src/navigators/createMaterialTopTabNavigator.js
[react-native-tab-view](https://github.com/react-native-community/react-native-tab-view) provides some pager alternatives like `PagerExperimental` but we can't use it with `react-navigation-tabs` because it always overrides `renderPager` prop with `undefined`.
When `useNativeDriver={true}`, built-in `MaterialTopTabBar` not working because `color` style prop not supported by native animation.
```js
createMaterialTopTabNavigator({
...
}, {
tabBarComponent: CustomTabBarComponent,
renderPager: props => <PagerExperimental {...props} {GestureHandler} userNativeDriver={true} />
})
```
> Fix renderPager undefined override

- src/navigators/createBottomTabNavigator.js
- src/views/ResourceSavingScene.js
When using react-native screens we don't need to hide invisible tabs using opacity. This in conjunctions with "active" property normally used by screens where causing blinking effect when new tabs got activated as in some cases opacity would update in a different UI transaction (this would only surface on Android).
This change removes the use of `opacity` style when react-native-screens are active and solely relies on `active` property in that case. When rn-screens are off we fallback to rendering `View` and use `opacity` as before (this is now done in `ResourceSavingScene`).
Fix blinking effect on Android when switching tabs [#5382](https://github.com/react-navigation/react-navigation/issues/5382)
1) Run RN-screens sample app with and w/o screens enabled or try the code from this snack …
> Change opacity for hidden tabs only when not using rn-screens

- src/views/BottomTabBar.js
The problem this fixes is that if you currently tap just slightly above the tab bar, the button in the tab bar is going to respond to the tap - and it should not.
Two reasons for this change:
1) it breaks detox e2e test in the case when there is a tab navigator, and the screen in it has a scrollview that we're trying to scroll down (` await element(by.id('someScrollView')).scrollTo('bottom');`)
The reason this doesn't work is that when detox tries to tap and drag the scrollView, detox taps just above the tab bar - within the reach of the hitslop - and instead of the scrollview responding, the scroll ends up being ignored.
2) if you take a look at a native app such as files, you'll see that taps outside the bounds of the tab bar are ignored. It should be the same for the tabs in …
> fix hit slop for bottom tab bar

- src/navigators/createBottomTabNavigator.js
- src/views/BottomTabBar.js
Exposing `accessibilityRole` and `accessibilityStates` through props in the same way as `accessibilityLabel`. This allows screen readers to announce things like: `Selected. Banana. Button.`
Reasonable defaults were provided, however, consumers can provide custom overrides in the cases where the role might be `imagebutton` or the state might be `disabled`.
Select a button with VoiceOver (iOS) or Talkback (Android) enabled. The screen reader should read something like `Selected. <AccessibilityLabel>. Button.` or something slightly different depending on which platform you are on. Buttons that are not focused should not have `Selected` announced.
> Adding accessibility role and state to bottom bar

- src/views/BottomTabBar.js
The BottomTabBar options allow for very fined grained customization but were missing a couple extension point to allow apps to override whether labels should be rendered beneath or beside the icon
- Verify the horizontal prop is available to `tabBarLabel` option.
- Verify `shouldRenderLabelBeneath` option can be used to override the default behavior.
> Add ability to customize whether label should be rendered beneath or beside icon

- src/views/BottomTabBar.js
Fixes #113 (increase padding for labels beside when emulating iOS horizontal label alignment).
> fix: increase padding for iOS horizontal label alignment

- example/package.json
- example/yarn.lock
- package.json
- src/utils/createTabNavigator.js
- yarn.lock
The index change event fires after swipe animation. If you quickly navigate to a new screen in stack before animation finishes, the index change event will fire after the previous navigation event. By this time, the tab navigator is not focused anymore. Using the JUMP_TO action instead of NAVIGATE avoids this issue.
> fix: use the JUMP_TO action for tab change

- src/index.tsx
You can't import BottomTabBarProps from
`import { BottomTabBarProps } from 'react-navigation-tabs'`
Try to import `BottomTabBarProps` from `react-navigation-tabs`
Fixes #187
> feat: export BottomTabBarProps

- src/utils/withDimensions.tsx
When starting the app in landscape mode and then switch to portrait the calculation of the tab bar dimensions are incorrect
1. Start the example app in landscape
2. Turn the phone back to portrait
3. Enter the "Bottom tabs" example
> fix: fix layout when starting in landscape

- src/views/BottomTabBar.tsx
this fixes #206
tested locally, please see the videos here [before-and-after.zip](https://github.com/react-navigation/tabs/files/3876932/before-and-after.zip)
related https://github.com/react-navigation/tabs/commit/c8e1cd24bd92bc51ed916d2e07feae39be3b3757#diff-df8db9f0a4883d10ede795953bd329bb
> fix: white block when keyboard is open

- example/App.tsx
- example/src/Shared/Chat.tsx
- example/src/Shared/Contacts.tsx
When following the readme instructions, example app fails with `module appregistry is not a registered callable module` I noticed there was a recent commit that broke this for me https://github.com/react-navigation/tabs/commit/8b9aa68b65a29b284cabd9a1fd6e71183e88eea8
I also added a TextInput that I wanted to use to test behavior of tab bar when keyboard it up, but noticed that the content stays hidden behind the keyboard, is this an expo thing? (vanilla RN moves content above keyboard). Thanks!
following the readme, example app works
> fix: make it possible to run example app
